# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './first.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mocap(object):
    def setupUi(self, Mocap):
        Mocap.setObjectName("Mocap")
        Mocap.resize(1219, 840)
        self.centralwidget = QtWidgets.QWidget(Mocap)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1101, 781))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        Mocap.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mocap)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1219, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Mocap.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mocap)
        self.statusbar.setObjectName("statusbar")
        Mocap.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Mocap)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 50))
        self.toolBar.setMovable(True)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setIconSize(QtCore.QSize(30, 50))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        Mocap.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(Mocap)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Dir = QtWidgets.QAction(Mocap)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")
        self.actionSave_Dir = QtWidgets.QAction(Mocap)
        self.actionSave_Dir.setObjectName("actionSave_Dir")
        self.actionQuit = QtWidgets.QAction(Mocap)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Dir)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Dir)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen_Dir)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave_Dir)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()

        self.retranslateUi(Mocap)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Mocap)

    def retranslateUi(self, Mocap):
        _translate = QtCore.QCoreApplication.translate
        Mocap.setWindowTitle(_translate("Mocap", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Mocap", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Mocap", "Tab 2"))
        self.menuFile.setTitle(_translate("Mocap", "File"))
        self.toolBar.setWindowTitle(_translate("Mocap", "toolBar"))
        self.actionOpen.setText(_translate("Mocap", "Open"))
        self.actionOpen_Dir.setText(_translate("Mocap", "Open Dir"))
        self.actionSave_Dir.setText(_translate("Mocap", "Save Dir"))
        self.actionQuit.setText(_translate("Mocap", "Quit"))
